/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BankableAIScreen`; params?: Router.UnknownInputParams; } | { pathname: `/BankableVirtualPetScreen`; params?: Router.UnknownInputParams; } | { pathname: `/DynamicBudgetCalendarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/EcoFinancialImpactScreen`; params?: Router.UnknownInputParams; } | { pathname: `/GroupSavingGoalsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/InvestmentsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LifeEventSupportScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Loans`; params?: Router.UnknownInputParams; } | { pathname: `/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/BankableAIScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/BankableVirtualPetScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/DynamicBudgetCalendarScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/EcoFinancialImpactScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/GroupSavingGoalsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/InvestmentsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/LifeEventSupportScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Loans`; params?: Router.UnknownOutputParams; } | { pathname: `/SettingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/BankableAIScreen${`?${string}` | `#${string}` | ''}` | `/BankableVirtualPetScreen${`?${string}` | `#${string}` | ''}` | `/DynamicBudgetCalendarScreen${`?${string}` | `#${string}` | ''}` | `/EcoFinancialImpactScreen${`?${string}` | `#${string}` | ''}` | `/GroupSavingGoalsScreen${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `/InvestmentsScreen${`?${string}` | `#${string}` | ''}` | `/LifeEventSupportScreen${`?${string}` | `#${string}` | ''}` | `/Loans${`?${string}` | `#${string}` | ''}` | `/SettingsScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BankableAIScreen`; params?: Router.UnknownInputParams; } | { pathname: `/BankableVirtualPetScreen`; params?: Router.UnknownInputParams; } | { pathname: `/DynamicBudgetCalendarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/EcoFinancialImpactScreen`; params?: Router.UnknownInputParams; } | { pathname: `/GroupSavingGoalsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/InvestmentsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LifeEventSupportScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Loans`; params?: Router.UnknownInputParams; } | { pathname: `/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
